create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('photo', 'video', 'audio')),
  favorite boolean not null default false,
  added_at bigint not null,
  storage_path text not null,
  public_url text not null
);

alter table public.memories enable row level security;

create policy "memories can be read by anyone with the link"
  on public.memories for select using (true);
create policy "memories can be added by anyone with the link"
  on public.memories for insert with check (true);
create policy "memories can be renamed or favorited by anyone with the link"
  on public.memories for update using (true) with check (true);
create policy "memories can be deleted by anyone with the link"
  on public.memories for delete using (true);

-- In Storage, create a public bucket named: memories
-- Then add these Storage policies for the memories bucket:
create policy "memory files can be uploaded"
  on storage.objects for insert to anon
  with check (bucket_id = 'memories');
create policy "memory files can be viewed"
  on storage.objects for select to anon
  using (bucket_id = 'memories');
create policy "memory files can be replaced"
  on storage.objects for update to anon
  using (bucket_id = 'memories');
create policy "memory files can be deleted"
  on storage.objects for delete to anon
  using (bucket_id = 'memories');